version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         echo "p0s1lka10" | docker login --username ayanochkin --password-stdin
       #docker run -d --name flaskex1 ayanochkin/flaskex:2.0

     # build the application image
     - run: docker build -t ayanochkin/flaskex:2.0 .

     # deploy the image
     - run: docker push ayanochkin/flaskex:2.0

